bind 0.0.0.0
protected-mode no
port 6379

replica-read-only yes

appendonly yes
appendfsync everysec

maxmemory 256mb
maxmemory-policy volatile-lru

# После failover реплика станет мастером, поэтому защита нужна и здесь
min-replicas-to-write 1
min-replicas-max-lag 10
